// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 1, duration: '30s', vus: 30 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    api: "http://localhost:5322"
  }
});

export default function() {
  postman[Request]({
    name: "Create Pessoa",
    id: "bbb223ee-47a0-4ae7-97b2-cb2db8e10631",
    method: "POST",
    address: "{{api}}/Pessoa",
	headers: {
      'Content-Type': 'application/json',
    },
    data:
      '{\r\n    "Nome": "Rafael",\r\n    "CPF": "103",\r\n    "Email": "email@email.com",\r\n    "DataNascimento": "1991-02-02"\r\n}'
  });
}
